# Generated by Django 5.2.8 on 2025-11-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Curso')),
                ('descripcion_corta', models.CharField(max_length=300, verbose_name='Descripción Breve')),
                ('precio_normal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_oferta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos/', verbose_name='Imagen del Curso')),
                ('categoria', models.CharField(choices=[('Tributaria', 'Tributaria'), ('Contable', 'Contable'), ('Laboral', 'Laboral'), ('Excel', 'Excel/Ofimática')], default='Contable', max_length=100)),
            ],
        ),
    ]
