# Generated by Django 5.2.8 on 2025-11-29 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_curso_descripcion_corta_curso_destacado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='objetivo',
            field=models.TextField(default='Brindar herramientas...', verbose_name='Objetivo del Curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='temario',
            field=models.TextField(default='<ul><li>Módulo 1...</li></ul>', help_text='Puedes usar etiquetas HTML básicas', verbose_name='Temario (HTML)'),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('pagado', models.BooleanField(default=False, verbose_name='¿Pago Validado?')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
